name: Determine bump level between two release tags

on:
  push:
    tags: [ 'v[0-9].[0-9].[0-9]' ]

defaults:
  run:
    shell: bash

jobs:
  determine_bump_level:
    name: Determine bump level
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Determine version bump value
      id: version-bump-value
      uses: ./.github/actions/determine-bump-level
      with:
        token: ${{ secrets.WORKFLOW_USER_GH_TOKEN }}

    - name: Create a workflow_dispatch event in redis-operator-helm repo
      run: |
        curl --request POST \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer ${{ secrets.WORKFLOW_USER_GH_TOKEN }}" \
          --url https://api.github.com/repos/sap/redis-operator-helm/actions/workflows/bump-version.yaml/dispatches \
          --data '{
            "ref":"main",
            "inputs":{
              "version-bump":"${{ steps.version-bump-value.outputs.bump-level }}"
              }
            }'
